# import requests
# import json
#
# text = ["""
# Creating an artificial intelligence aid for music composers requires a practical and modular approach that allows the composer to manipulate the technology as needed in the search for new sounds and ideas. Many existing approaches fail to capture the interest of composers as they are limited beyond their demonstrative purposes or allow minimal interaction with the composer. Score-Transformer (ST) demonstrates a practical integration of artificial intelligence to aid in the creation of new music by working seamlessly alongside any popular notation software. Furthermore, ST can be trained by the user with additional works (including their own compositions), fine-tuning it and minimizing the risk of the software becoming outdated or impractical for continued use. ST was used in the creation of my dissertation piece, Music for Self-Attention.
# Music for Self-Attention features an innovative algorithmic approach to traditional compositional methods by demonstrating the benefits of using deep learning in music composition to aid with certain pitch and rhythmic decisions. These artificially generated decisions were not intended to fully remove the human element from composing but rather to work in tandem with the composer, in this case, myself. The piece lasts approximately 23 minutes and loosely follows a form of theme and variations in reverse. This steady process gradually deconstructs a series of variations which were each initially generated by artificial means until the final movement—containing no artificial intervention—is revealed. This is not a theme and variations in the usual way as the listener won’t hear the theme in each variation. Each movement reflects different processes involved in the training and deployment of artificially intelligent software. Music for Self-Attention is meant to demonstrate a symbiotic relationship that can exist between artificial and human creativity in music composition.
# """, """First, I would like to thank my girlfriend Beth Copeland, whose love and support throughout my PhD was integral to its success (especially during times of seemingly unfixable code breaks). I could not have completed this work without you.
# Next to my parents Natalie Allen and Steve Lupker, who have edited countless papers, proposals and applications throughout my eleven years in university. Also, for inspiring me to pursue a career in academia.
# To Dr. William J. Turkel I would like to thank you for all of the support during my degree and throughout my dissertation. I look forward to our continued research and co- publications together.
# I would like to say a special thank you to my supervisor Dr. Paul Frehner for all of your help throughout the last five years of my degree. I am very grateful for all of the time you have spent helping me with my research, writing recommendation letters and all of the guidance you have provided me along the way.""", """The Calgary Stampede and Alberta Health said Tuesday that 71 people contracted COVID-19 at the 2021 event — but that may be an underestimate, according to the province’s former top doctor.
#
#
# READ MORE: Calgary live events industry reflects on Calgary Stampede
#
# This represents about seven cases per day or a total of 0.01 per cent of 528,998 attendees, the Stampede said.
#
# “This year, our community celebration was the first step in the safe return of live events for our city and our country,” said interim CEO Dana Peers in a news release.
#
# “We believe Stampede 2021 was a success.
#
# TWEET THIS
# CLICK TO SHARE QUOTE ON TWITTER: "WE BELIEVE STAMPEDE 2021 WAS A SUCCESS.
# “We committed to operating safely, and these results show the effectiveness of the enhanced safety measures that were put in place,” including rapid testing and reduced park capacity.
#
# Crowds build during the Calgary Stampede on Friday, July 9, 2021.View image in full screen
# Crowds build during the Calgary Stampede on Friday, July 9, 2021. THE CANADIAN PRESS/Jeff McIntosh
# Dr. Jia Hu, a public health physician advising the Stampede, said the festival went “above and beyond” with safety measures.
#
# READ MORE: Calgary Stampede officials say they pulled off a pandemic success
#
# “In context, over the past two weeks, 749 cases were reported across Alberta. The low number of cases associated with the Stampede is not unexpected and reinforces the safe operating measures put in place along with the effectiveness of vaccines,” she said in the news release.
#
# Tom McMillan, assistant director of communications at Alberta Health, echoed Hu’s comments about vaccines and the “diligent way” organizers applied public health measures.
#
# READ MORE: COVID-19: Events sector keeps eye on Calgary Stampede to see if mass gatherings can be held safely
#
# “While a small number of cases were identified, the Calgary Stampede so far does not appear to have been a significant driver of rising COVID-19 cases in the province,” he said via email.
#
# Click to play video: 'Calgary event planners reflect on 2021 Calgary Stampede'
# 1:50
# Calgary event planners reflect on 2021 Calgary Stampede
# Calgary event planners reflect on 2021 Calgary Stampede – Jul 19, 2021
# ‘Likely an underestimate’
# But Alberta’s former chief medical officer of health says we haven’t seen the spike in cases yet. Dr. James Talbot presumes the 71 cases were from people who were tested and contact traced.
#
# “Since we know some people are asymptomatic and mildly symptomatic and unlikely to have been tested, it is likely an underestimate — not to mention that activities associated with the Stampede, like bar hopping, would still cause cases but would not be traced as ‘was at the Stampede,'” Talbot said via email.
#
# READ MORE: COVID-19: Doctors’ group concerned about Calgary Stampede, major corporate partner won’t take part
#
# The Stampede ran July 9-18.
#
# “Cases tend to show up about two weeks after the exposure. The first would have started showing up on July 23 and the end was July 19, so those would continue to show up until Aug. 2,” Talbot said."""]
#
# r = requests.get(f'http://127.0.0.1:5000/summarize?text={text}')
# print(r.json())